# Keycloak Configuration
keycloak.auth-server-url=http://localhost:8080/auth
keycloak.realm=your-realm
keycloak.resource=your-client-id
keycloak.credentials.secret=your-client-secret
keycloak.ssl-required=external
keycloak.public-client=false
keycloak.confidential-port=0