spring:
  datasource:
    keycloak:
      jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:elearning_common_prod}?currentSchema=keycloak
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}
    main:
      jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:elearning_common_prod}?currentSchema=public
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}

services:
  auth-service:
    url: http://localhost:8085
  cart-service:
    url: http://localhost:8082
  notification-service:
    url: http://localhost:8083
  course-service:
    url: http://localhost:8081
  common-service:
    url: http://localhost:8084
  tutor-service:
    url: http://localhost:8086
# Định nghĩa logging trong local
logging:
  level:
    root: INFO
    "[com.elearning.apigateway]": DEBUG
