server.port=8083

spring.application.name=learner-bff-service

# Redis config (for caching)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000

# Downstream services base URLs
service.learner.base-url=http://localhost:8082/api/v1/learners
service.course.base-url=http://localhost:8084/api/v1/courses
service.cart.base-url=http://api-gateway/api/v1/cart
service.quiz.base-url=http://localhost:8085/api/v1/quiz
service.user.base-url=http://localhost:8081/api/v1/users

# Logging
logging.level.com.elearning=DEBUG

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
