-- React and remaining courses lessons

-- Course 4, Section 1 Lessons (React Fundamentals)
INSERT INTO lessons (id, section_id, course_id, title, description, duration, is_completed, is_current, is_locked, video_url, content, order_index, created_at, updated_at) VALUES
('lesson-33', 'react-section-1', 'course-4', 'Introduction to React', 'Get started with React and understand its core concepts.', '6 mins', true, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', '', 1, NOW(), NOW()),
('lesson-34', 'react-section-1', 'course-4', 'JSX and Components', 'Learn JSX syntax and how to create reusable components.', '8 mins', true, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', '', 2, NOW(), NOW()),
('lesson-35', 'react-section-1', 'course-4', 'Props and State', 'Master props and state management in React components.', '10 mins', true, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', '', 3, NOW(), NOW()),
('lesson-36', 'react-section-1', 'course-4', 'Event Handling', 'Handle user interactions and events in React applications.', '7 mins', true, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', '', 4, NOW(), NOW()),
('lesson-37', 'react-section-1', 'course-4', 'Conditional Rendering', 'Learn how to conditionally render content in React.', '6 mins', true, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', '', 5, NOW(), NOW()),
('lesson-38', 'react-section-1', 'course-4', 'Lists and Keys', 'Render lists efficiently with proper key usage.', '8 mins', false, true, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', '', 6, NOW(), NOW()),
('lesson-39', 'react-section-1', 'course-4', 'React Hooks - useState', 'Master the useState hook for state management in functional components.', '9 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', '', 7, NOW(), NOW()),
('lesson-40', 'react-section-1', 'course-4', 'React Hooks - useEffect', 'Learn useEffect hook for side effects and lifecycle management.', '11 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', '', 8, NOW(), NOW()),
('lesson-41', 'react-section-1', 'course-4', 'Custom Hooks', 'Create and use custom hooks to share logic between components.', '7 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', '', 9, NOW(), NOW()),
('lesson-42', 'react-section-1', 'course-4', 'Context API', 'Manage global state with React Context API.', '10 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', '', 10, NOW(), NOW());

-- Course 4, Section 2 Lessons (React Advanced)
INSERT INTO lessons (id, section_id, course_id, title, description, duration, is_completed, is_current, is_locked, video_url, content, order_index, created_at, updated_at) VALUES
('lesson-43', 'react-section-2', 'course-4', 'useReducer and Complex State Management', 'Learn useReducer for managing complex state logic with reducers.', '9 mins', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', '', 1, NOW(), NOW()),
('lesson-44', 'react-section-2', 'course-4', 'React.memo and Performance Optimization', 'Optimize component performance with React.memo and memoization techniques.', '8 mins', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', '', 2, NOW(), NOW()),
('lesson-45', 'react-section-2', 'course-4', 'useCallback and useMemo Hooks', 'Master useCallback and useMemo for optimizing performance and preventing unnecessary re-renders.', '10 mins', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', '', 3, NOW(), NOW()),
('lesson-46', 'react-section-2', 'course-4', 'Error Boundaries and Error Handling', 'Implement error boundaries to catch and handle errors gracefully in React applications.', '9 mins', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', '', 4, NOW(), NOW()),
('lesson-47', 'react-section-2', 'course-4', 'React Patterns and Best Practices', 'Learn advanced React patterns and best practices for building scalable applications.', '9 mins', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', '', 5, NOW(), NOW());

-- Course 5, Section 1 Lessons (Design Thinking)
INSERT INTO lessons (id, section_id, course_id, title, description, duration, is_completed, is_current, is_locked, video_url, content, order_index, created_at, updated_at) VALUES
('lesson-48', 'design-section-1', 'course-5', 'What is Design Thinking?', 'Introduction to design thinking methodology and its benefits.', '5 mins', false, true, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', '', 1, NOW(), NOW()),
('lesson-49', 'design-section-1', 'course-5', 'The 5 Stages of Design Thinking', 'Learn the five stages: Empathize, Define, Ideate, Prototype, and Test.', '6 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', '', 2, NOW(), NOW()),
('lesson-50', 'design-section-1', 'course-5', 'Empathy in Design', 'Understand the importance of empathy in the design process.', '4 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', '', 3, NOW(), NOW()),
('lesson-51', 'design-section-1', 'course-5', 'Problem Definition', 'Learn how to define problems clearly and effectively.', '3 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', '', 4, NOW(), NOW()),
('lesson-52', 'design-section-1', 'course-5', 'Ideation Techniques', 'Master various ideation techniques like brainstorming and mind mapping.', '7 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', '', 5, NOW(), NOW()),
('lesson-53', 'design-section-1', 'course-5', 'Prototyping and Testing', 'Learn how to create prototypes and test your ideas effectively.', '8 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', '', 6, NOW(), NOW()),
('lesson-54', 'design-section-1', 'course-5', 'User Research Methods', 'Explore different user research methods and when to use them.', '6 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', '', 7, NOW(), NOW()),
('lesson-55', 'design-section-1', 'course-5', 'Design Thinking Tools', 'Discover useful tools and frameworks for design thinking.', '5 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', '', 8, NOW(), NOW());

-- Course 5, Section 2 Lessons (Design Thinking Advanced)
INSERT INTO lessons (id, section_id, course_id, title, description, duration, is_completed, is_current, is_locked, video_url, content, order_index, created_at, updated_at) VALUES
('lesson-56', 'design-section-2', 'course-5', 'Rapid Prototyping and Testing', 'Learn how to create rapid prototypes and test them with users effectively.', '5 mins', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', '', 1, NOW(), NOW()),
('lesson-57', 'design-section-2', 'course-5', 'Iterating Based on Feedback', 'Master the art of iterating and improving solutions based on user feedback.', '5 mins', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4', '', 2, NOW(), NOW()),
('lesson-58', 'design-section-2', 'course-5', 'Implementing Design Thinking in Organizations', 'Learn how to implement design thinking methodologies in your organization.', '5 mins', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4', '', 3, NOW(), NOW()),
('lesson-59', 'design-section-2', 'course-5', 'Measuring Design Thinking Success', 'Discover how to measure the success and impact of design thinking initiatives.', '5 mins', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4', '', 4, NOW(), NOW());

-- Course 6, Section 1 Lessons (Business Strategy)
INSERT INTO lessons (id, section_id, course_id, title, description, duration, is_completed, is_current, is_locked, video_url, content, order_index, created_at, updated_at) VALUES
('lesson-60', 'business-section-1', 'course-6', 'What is Business Strategy?', 'Introduction to business strategy and its importance in organizational success.', '4 mins', false, true, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', '', 1, NOW(), NOW()),
('lesson-61', 'business-section-1', 'course-6', 'SWOT Analysis', 'Master SWOT analysis to assess your business strengths, weaknesses, opportunities, and threats.', '5 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', '', 2, NOW(), NOW()),
('lesson-62', 'business-section-1', 'course-6', 'Competitive Analysis', 'Learn how to analyze competitors and identify competitive advantages.', '4 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', '', 3, NOW(), NOW()),
('lesson-63', 'business-section-1', 'course-6', 'Market Positioning', 'Understand market positioning strategies and how to differentiate your business.', '5 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', '', 4, NOW(), NOW()),
('lesson-64', 'business-section-1', 'course-6', 'Strategic Goals Setting', 'Set clear, measurable strategic goals that align with your business vision.', '4 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', '', 5, NOW(), NOW()),
('lesson-65', 'business-section-1', 'course-6', 'Resource Allocation', 'Learn how to allocate resources effectively to achieve strategic objectives.', '6 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', '', 6, NOW(), NOW()),
('lesson-66', 'business-section-1', 'course-6', 'Risk Management', 'Identify and manage risks that could impact your business strategy.', '5 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', '', 7, NOW(), NOW()),
('lesson-67', 'business-section-1', 'course-6', 'Strategic Implementation', 'Learn how to implement and execute your business strategy effectively.', '7 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', '', 8, NOW(), NOW()),
('lesson-68', 'business-section-1', 'course-6', 'Performance Measurement', 'Establish KPIs and metrics to measure strategic performance.', '4 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', '', 9, NOW(), NOW()),
('lesson-69', 'business-section-1', 'course-6', 'Strategic Planning Tools', 'Explore various tools and frameworks for strategic planning.', '6 mins', false, false, false, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', '', 10, NOW(), NOW());

-- Course 6, Section 2 Lessons (Business Strategy Advanced)
INSERT INTO lessons (id, section_id, course_id, title, description, duration, is_completed, is_current, is_locked, video_url, content, order_index, created_at, updated_at) VALUES
('lesson-70', 'business-section-2', 'course-6', 'Scenario Planning and Future Thinking', 'Learn scenario planning techniques to prepare for multiple possible futures.', '5 mins 30 sec', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', '', 1, NOW(), NOW()),
('lesson-71', 'business-section-2', 'course-6', 'Strategy Execution and Change Management', 'Master the art of executing strategy and managing organizational change.', '5 mins 45 sec', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', '', 2, NOW(), NOW()),
('lesson-72', 'business-section-2', 'course-6', 'Balanced Scorecard and Performance Management', 'Implement balanced scorecard methodology for comprehensive performance management.', '5 mins 30 sec', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', '', 3, NOW(), NOW()),
('lesson-73', 'business-section-2', 'course-6', 'Strategic Leadership and Culture', 'Build strategic leadership capabilities and create a culture that supports strategy execution.', '5 mins 15 sec', false, false, true, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4', '', 4, NOW(), NOW());
