spring:
  application:
    name: notification-service
  profiles:
    active: dev
server:
  port: 8083

logging:
  level:
    root: INFO
    "[org.springframework.web]": DEBUG
  file:
    name: logs/notification-service.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
