spring:
  data:
    mongodb:
      uri: mongodb+srv://hunghoang:root123456@lms.1zh4ll5.mongodb.net
      database: notification_db

  mail:
    host: smtp.gmail.com
    port: 587
    username: viethunghoang1508@gmail.com
    password: icmxnpujolermyye
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
