spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: tutor
        

gemini:
  api-key: AIzaSyDRUFCJA2ZtNYRjOniJdAnGhgUTOa1uHcI
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

services:
  auth-service:
    url: ${AUTH_SERVICE_URL}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL}
  common-service:
    url: ${COMMON_SERVICE_URL}

zoom:
  oauth:
    client-id: ${ZOOM_CLIENT_ID:12Vtzm5XSNqb21sZfzzfvA}
    client-secret: ${ZOOM_CLIENT_SECRET:Bo1SkrrNbr2qQ1Sg7LecESkOQLsAW2eE}
    redirect-uri: ${ZOOM_REDIRECT_URI:http://localhost:5173/dashboard/profile-settings/personal-details}
    authorize-url: https://zoom.us/oauth/authorize
    token-url: https://zoom.us/oauth/token
  api:
    base-url: https://api.zoom.us/v2
  meeting:
    default-duration: 60
    waiting-room: true
