# ---- Stage 1: Build (Maven + Java)
FROM maven:3.9.9-eclipse-temurin-17-alpine AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn -B dependency:go-offline
COPY src ./src
RUN mvn -B clean package -DskipTests

# ---- Stage 2: Run (Java + FFmpeg)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Cài FFmpeg
RUN apk add --no-cache ffmpeg

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080
CMD exec java -Xms128m -Xmx350m -jar app.jar
