spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: bff-route
              uri: ${BFF_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/v1/common/**

            - id: auth-service-route
              uri: ${AUTH_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/api/auth/**

            - id: user-service-route
              uri: ${USER_SERVICE_URI:http://localhost:8083}
              predicates:
                - Path=/api/users/**

            - id: course-service-route
              uri: ${COURSE_SERVICE_URI:http://localhost:8084}
              predicates:
                - Path=/api/courses/**