spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  cloud:
    gateway:
      routes:
        - id: bff-route
          uri: ${BFF_SERVICE_URL}
          predicates:
            - Path=/api/v1/**
            - Path=/api/v1/public/**
          filters:
            - RewritePath=/api/v1/public/(.*), /api/v1/bff/$1

        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**