spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  cloud:
    gateway:
      routes:
        - id: bff-route
          uri: ${BFF_SERVICE_URL}
          predicates:
            - Path=/api/v1/web/**
            - Path=/api/v1/public/**
            - Path=/api/v1/tutors/**
          filters:
            - RewritePath=/api/v1/(web|public|tutors)/(.*), /api/v1/bff/$2

        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**

services:
  bff-service:
    url: ${BFF_SERVICE_URL}
  auth-service:
    url: ${AUTH_SERVICE_URL}
  cart-service:
    url: http://cart-service:8082
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL}
  course-service:
    url: ${COURSE_SERVICE_URL}
  common-service:
    url: ${COMMON_SERVICE_URL}
  tutor-service:
    url: ${TUTOR_SERVICE_URL}
  class-service:
    url: ${CLASS_SERVICE_URL}
  user-service:
    url: ${USER_SERVICE_URL}
  student-service:
    url: ${STUDENT_SERVICE_URL}
  search-service:
    url: ${SEARCH_SERVICE_URL:http://search-service:8086}
  chat-service:
    url: ${CHAT_SERVICE_URL}
  payment-service:
    url: ${PAYMENT_SERVICE_URL:http://payment-service:8091}
  booking-service:
    url: ${BOOKING_SERVICE_URL:http://booking-service:8092}