spring:
  redis:
    url: rediss://red-d42g8bbuibrs73dv5ou0:HopCfDDFzZhoWeOgf5jZ9vKWNVtmxzqZ@singapore-keyvalue.render.com:6379

notification-service:
  url: http://localhost:8085

jwt:
  secret: mySuperSecretKeyForInternalJwtThatIsAtLeast256BitsLongEnough
  expiry: 600000

keycloak:
  auth-server-url: http://localhost:8080
  realm: elearning
  resource: auth-service
  client-secret: your-client-secret
  admin-username: admin
  admin-password: admin