spring:
  data:
    redis:
      url: redis://redis:6379
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: auth-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

notification-service:
  url: ${NOTIFICATION_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}
  expiry: ${JWT_EXPIRY}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  public-url: ${KEYCLOAK_PUBLIC_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  client-secret: YyfwTayJUBYIxT0rLMbynjqg6pSG7KiZ