spring:
  data:
    redis:
      url: localhost:6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

notification-service:
  url: http://localhost:8085

jwt:
  secret: mySuperSecretKeyForInternalJwtThatIsAtLeast256BitsLongEnough
  expiry: 600000

keycloak:
  auth-server-url: http://localhost:8080
  public-url: http://localhost:8080
  realm: lernen
  resource: auth-service
  client-secret: your-client-secret
  admin-username: admin
  admin-password: admin