spring:
  data:
    redis:
      url: ${REDIS_URL}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    # producer:
    #   key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #   value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: auth-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

notification-service:
  url: ${NOTIFICATION_SERVICE_URL}

jwt:
  secret: ${JWT_SECRET}
  expiry: ${JWT_EXPIRY}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  public-url: ${KEYCLOAK_PUBLIC_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}