server:
  port: 3000

spring:
  main:
    web-application-type: servlet

services:
  cart:
    base-url: ${CART_SERVICE_URL}
  course:
    base-url: ${COURSE_SERVICE_URL}
  learner:
    base-url: ${LEARNER_SERVICE_URL}
  auth:
    base-url: ${AUTH_SERVICE_URL}
  notification:
    base-url: ${NOTIFICATION_SERVICE_URL}

logging:
  level:
    root: WARN
    "[com.elearning.apigateway]": INFO
