spring:
  data:
    mongodb:
      uri: ${MONGO_URI}chat_db?retryWrites=true&w=majority
services:
  auth-service:
    url: ${AUTH_SERVICE_URL}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL}
  common-service:
    url: ${COMMON_SERVICE_URL}
  tutor-service:
    url: ${TUTOR_SERVICE_URL}

logging:
  level:
    root: INFO
    "[com.elearning.bffservice]": DEBUG
