spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:elearning_common_prod}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

services:
  auth-service:
    url: http://localhost:8085
  cart-service:
    url: http://localhost:8082
  notification-service:
    url: http://localhost:8083
  course-service:
    url: http://localhost:8081
  common-service:
    url: http://localhost:8084
  tutor-service:
    url: http://localhost:8086
# Định nghĩa logging trong local
logging:
  level:
    root: INFO
    "[com.elearning.apigateway]": DEBUG
