spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: quiz
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

gemini:
  api-key: AIzaSyBUrfegv95-EBBPKo-1Jobpg368E0WN3lU
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

services:
  auth-service:
    url: ${AUTH_SERVICE_URL}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL}
  common-service:
    url: ${COMMON_SERVICE_URL}
  tutor-service:
    url: ${TUTOR_SERVICE_URL}

logging:
  level:
    root: INFO
    "[com.elearning.bffservice]": DEBUG