server:
  port: 8084

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://username:password@cluster0.mongodb.net/lms_chat_db?retryWrites=true&w=majority}

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.elearning.chatservice: INFO

# CORS handled at API Gateway
app:
  cors:
    allowed-origins: "https://lms-prod.com"
  swagger:
    enabled: false   # ❌ không bật swagger trên prod