INSERT INTO categories (name, description, icon_name, is_active, created_at, updated_at) VALUES
('Programming', 'Learn programming languages and software development', 'programming', true, NOW(), NOW()),
('Design', 'Graphic design, UI/UX design, and creative arts', 'design', true, NOW(), NOW()),
('Business', 'Business management, entrepreneurship, and marketing', 'business', true, NOW(), NOW()),
('Language', 'Foreign languages and communication skills', 'language', true, NOW(), NOW()),
('Photography', 'Digital photography and photo editing techniques', 'photography', true, NOW(), NOW()),
('Music', 'Music theory, instruments, and audio production', 'music', true, NOW(), NOW()),
('Data Science', 'Data analysis, machine learning, and statistics', 'data-science', true, NOW(), NOW()),
('Web Development', 'Frontend, backend, and full-stack web development', 'web-development', true, NOW(), NOW()),
('Mobile Development', 'iOS and Android mobile app development', 'mobile-development', true, NOW(), NOW()),
('Artificial Intelligence', 'AI, machine learning, and deep learning', 'artificial-intelligence', true, NOW(), NOW()),
('Cybersecurity', 'Information security and ethical hacking', 'cybersecurity', true, NOW(), NOW()),
('Cloud Computing', 'AWS, Azure, and cloud infrastructure', 'cloud-computing', true, NOW(), NOW()),
('UI/UX Design', 'User interface and user experience design', 'ui-ux', true, NOW(), NOW()),
('Digital Marketing', 'Online marketing and social media strategies', 'marketing', true, NOW(), NOW()),
('Finance', 'Financial planning and investment strategies', 'finance', true, NOW(), NOW()),
('Health & Fitness', 'Physical health, nutrition, and wellness', 'fitness', true, NOW(), NOW()),
('Cooking', 'Culinary arts and cooking techniques', 'cooking', true, NOW(), NOW()),
('Writing', 'Creative writing and content creation', 'writing', true, NOW(), NOW()),
('Mathematics', 'Advanced mathematics and problem solving', 'mathematics', true, NOW(), NOW()),
('Science', 'Physics, chemistry, and biological sciences', 'science', true, NOW(), NOW());