server:
  port: 8081
  
spring:
  application:
    name: course-servive
  datasource:
    url: jdbc:postgresql://db:5432/courses_db
    username: course_user
    password: course_pass
  jpa:
    hibernate:
      ddl-auto: update
