version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CART_SERVICE_URL=http://host.docker.internal:8081
      - NOTIFICATION_SERVICE_URL=http://host.docker.internal:8082
    networks:
      - elearning-network

networks:
  elearning-network:
    driver: bridge