# ====== SERVER ======
server.port=8083
spring.application.name=notification-service

# ====== MONGODB ======
spring.data.mongodb.uri=mongodb://localhost:27017/notification_db

# ====== EMAIL (SMTP Gmail) ======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoangtienhung30062003@gmail.com
spring.mail.password=yhbjtesyagzozccz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ====== LOGGING ======
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/notification-service.log

# Đường dẫn mặc định cho API docs và giao diện Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html