spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_db

  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangtienhung30062003@gmail.com
    password: yhbjtesyagzozccz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
