spring:
  application:
    name: cart-service
  datasource:
    url: ${POSTGRES_URL}          # Ví dụ: jdbc:postgresql://host:5432/cart_service_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
     "[hibernate.format_sql]": true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

