spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/cart_service_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
    database-platform: org.hibernate.dialect.MySQL8Dialect
# Disable Eureka client for local dev
eureka:
  client:
    enabled: false