
spring:
  application:
    name: cart-service
  profiles:
    active: prod
server:
  port: 8082
# Cấu hình chung cho Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Cấu hình URL của các service khác (giữ nguyên, override ở dev/pro nếu cần)
service:
  course-url: http://localhost:8081
  coupon-url: http://localhost:8082
  order-url: http://localhost:8083
