server:
  port: 8095

spring:
  application:
    name: health-check-service
  profiles:
    active: prod # Changed from prod to dev for local development

logging:
  level:
    root: INFO
    "[com.elearning.healthcheckservice]": DEBUG
