server:
  port: 8091
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: payment

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

services:
  auth-service:
    url: ${AUTH_SERVICE_URL}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL}
  common-service:
    url: ${COMMON_SERVICE_URL}
  tutor-service:
    url: ${TUTOR_SERVICE_URL}

payment:
  providers:
    momo:
      partnerCode: "MOMOI0ZT20251005_TEST"
      accessKey: "RAlqforIHMzHupmt"
      secretKey: "UeTsSYek1420zZmXpbinGDnTviPnditj"
      endpoint: "https://test-payment.momo.vn/v2/gateway/api"
    vnpay:
      tmn-code: "97IDADFL"
      hash-secret: "X4OOQTBSKPM75HI2CIFULM3AILRQFC7M"
      endpoint: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"