name: Frontend CI

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/lernen/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/lernen
          file: ./frontend/lernen/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lernen-frontend:latest
          
      - name: Trigger OnRender Deploy for Frontend
        run: curl -X POST ${{ secrets.ONRENDER_HOOK_FRONTEND }}
